Move the wineserver script from wine to libwine.
Closes: #932201

This ensures that Wine always finds its wineserver in its bindir.
Otherwise if wine was not installed it might fail to find it, or
fall back to another wineserver in e.g. PATH.

wine{32,64} would be better suited, but dpkg only accepts multiple
packages as owner of a file for "Multi-Arch: same" packages.

diff --git a/debian/scripts/wineserver.in b/debian/scripts/wineserver.in
--- a/debian/scripts/wineserver.in
+++ b/debian/scripts/wineserver.in
@@ -8,7 +8,8 @@ if test -x "$wineserver64"; then
 elif test -x "$wineserver32"; then
     wineserver=$wineserver32
 else
-    echo "error: unable to find wineserver executable.  this shouldn't happen." >&2
+    echo "error: unable to find wineserver executable." >&2
+    echo "wine32VERSION and/or wine64VERSION must be installed." >&2
     exit 1
 fi
 
